version: '3.8'

services:
  app1:
    image: node:18
    working_dir: /app
    volumes:
      - ./app1:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm start"
    environment:  
      - NODE_ENV=development

  app2:
    image: node:18
    working_dir: /app
    volumes:
      - ./app2:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development

  app3:
    image: node:18
    working_dir: /app
    volumes:
      - ./app3:/app
      - /app/node_modules
    ports:
      - "3003:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
      - app3

